# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release

cache: packages

stages:
  - Setup Cache
  - Test

# setup cache first
jobs:
  include:
    - stage: Setup Cache
      r: bioc-release
      install: 
        - R -e "
            if(!requireNamespace('BiocManager', quietly=TRUE)){
                install.packages('BiocManager');
            };
            if(!requireNamespace('R.utils', quietly=TRUE)){
                install.packages('R.utils');
            };
            if(!requireNamespace('devtools', quietly=TRUE)){
                install.packages('devtools');
            };
            R.utils::withTimeout(timeout=2400, { try({
                devtools::install_dev_deps(repos=BiocManager::repositories())
            }) });
            "
      script: true
    - stage: Test
      r: bioc-release

before_cache:
  # they are too big to be cached
  - R -e 'remove.packages("MafDb.gnomAD.r2.1.GRCh38")'
  - R -e 'remove.packages("MafDb.gnomAD.r2.1.hs37d5")'
